DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS investments CASCADE;

CREATE TABLE products
(
    id                     bigint       NOT NULL AUTO_INCREMENT, --id
    title                  varchar(100) NOT NULL,                --상품명
    total_investing_amount bigint       NOT NULL,                --총 투자 모집금액
    started_at             datetime     NOT NULL,                --투자시작일시
    finished_at            datetime     NOT NULL,                --투자종료일시
    PRIMARY KEY (id)
);


create table investments (
                             invest_id bigint generated by default as identity,
                             invest_amount bigint not null,
                             investment_date date,
                             investment_status varchar(255),
                             user_id bigint not null,
                             id bigint,
                             primary key (invest_id)
);

alter table investments
    add constraint FK_product_id
        foreign key (id)
            references products;